apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - image: jaegertracing/all-in-one:latest
          name: jaeger
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 14268
            - containerPort: 14250
            - containerPort: 16686
            

---

apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  ports:
    - name: "5775"
      port: 5775
      targetPort: 5775
      protocol: UDP
    - name: "6831"
      port: 6831      
      targetPort: 6831
      protocol: UDP
    - name: "6832"
      port: 6832
      targetPort: 6832
      protocol: UDP
    - name: "5778"
      port: 5778
      targetPort: 5778
    - name: "14268"
      port: 14268
      targetPort: 14268
    - name: "14250"
      port: 14250
      targetPort: 14250
    - name: "16686"
      port: 16686
      targetPort: 16686    
  selector:
    app: jaeger
  type: ClusterIP