apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-service
spec:
  selector:
    app: {{ .Release.Name }}-api
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      name: http
    - port: 443
      targetPort: 443
      name: https
  type: {{ .Values.api.serviceType }}