apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9216"
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4.5
        resources:
          requests:            
            memory: "256Mi"
            cpu: "128m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        ports:
        - containerPort: 27017
        volumeMounts:
          - mountPath: /data/db
            name: mongo-data
        envFrom:
            - secretRef:
                name: mongodb-secret
      - name: mongodbexporter
        image: fabricioveronez/mongo_exporter
        resources: {}
        ports:
          - containerPort: 9216
        env:
          - name: MONGODB_URI
            value: mongodb://mongouser:mongopwd@localhost:27017          
      volumes:
        - name: mongo-data
          hostPath:
            path: /volumes/mongodb
      